const data = {
	products: [
		{
			name: 'Peanuts - Anya Forger Keychain',
			slug: 'anya-keychain',
			category: 'Keychains',
			image: '/images/anya.png',
			price: 8.95,
			countInStock: 0,
			rating: '4.3',
			numReviews: '5',
			description: 'A cute keychain',
		},
		{
			name: 'Bready Bakerie',
			slug: 'bread-stickers',
			category: 'Sticker Sheet',
			image: '/images/bread.png',
			price: 3.25,
			countInStock: 10,
			rating: '4.3',
			numReviews: '5',
			description: 'A cute sticker sheet',
		},
		{
			name: 'Forest Friends Sticker Sheet',
			slug: 'forest-stickers',
			category: 'Sticker Sheet',
			image: '/images/forestfriends.png',
			price: 3.25,
			countInStock: 10,
			rating: '4.3',
			numReviews: '5',
			description: 'A cute sticker sheet',
		},
		{
			name: 'Strawberry Delights',
			slug: 'strawberry-stickers',
			category: 'Sticker Sheet',
			image: '/images/strawberry.png',
			price: 3.25,
			countInStock: 10,
			rating: '4.3',
			numReviews: '5',
			description: 'A cute sticker sheet',
		},
	],
};

export default data;
